let data = [
    {
        "id": 0,
        "declination": 1,
        "gender": "F",
        "nomSg": "silva",
        "genSg": "silvae",
        "datSg": "silvae",
        "accSg": "silvam",
        "ablSg": "silva",
        "nomPl": "silvae",
        "genPl": "silvarum",
        "datPl": "silvis",
        "accPl": "silvas",
        "ablPl": "silvis"
    },
    {
        "id": 1,
        "declination": 2,
        "gender": "M",
        "nomSg": "servus",
        "genSg": "servi",
        "datSg": "servo",
        "accSg": "servum",
        "ablSg": "servo",
        "nomPl": "servi",
        "genPl": "servorum",
        "datPl": "servis",
        "accPl": "servos",
        "ablPl": "servis"
    },
    {
        "id": 3,
        "declination": 2,
        "gender": "N",
        "nomSg": "bellum",
        "genSg": "belli",
        "datSg": "bello",
        "accSg": "bellum",
        "ablSg": "bello",
        "nomPl": "bella",
        "genPl": "bellorum",
        "datPl": "bellis",
        "accPl": "bella",
        "ablPl": "bellis"
    },
    {
        "id": 4,
        "declination": 3,
        "gender": "M",
        "nomSg": "miles",
        "genSg": "militis",
        "datSg": "militi",
        "accSg": "militem",
        "ablSg": "milite",
        "nomPl": "milites",
        "genPl": "militum",
        "datPl": "militibus",
        "accPl": "milites",
        "ablPl": "militibus"
    },
    {
        "id": 5,
        "declination": 4,
        "gender": "M",
        "nomSg": "fructus",
        "genSg": "fructus",
        "datSg": "fructui",
        "accSg": "fructum",
        "ablSg": "fructu",
        "nomPl": "fructus",
        "genPl": "fructuum",
        "datPl": "fructibus",
        "accPl": "fructus",
        "ablPl": "fructibus"
    },
    {
        "id": 6,
        "declination": 4,
        "gender": "N",
        "nomSg": "cornu",
        "genSg": "cornus",
        "datSg": "cornui",
        "accSg": "cornu",
        "ablSg": "cornu",
        "nomPl": "cornua",
        "genPl": "cornuum",
        "datPl": "cornibus",
        "accPl": "cornua",
        "ablPl": "cornibus"
    },
    {
        "id": 7,
        "declination": 5,
        "gender": "F",
        "nomSg": "res",
        "genSg": "rei",
        "datSg": "rei",
        "accSg": "rem",
        "ablSg": "re",
        "nomPl": "res",
        "genPl": "rerum",
        "datPl": "rebus",
        "accPl": "res",
        "ablPl": "rebus"
    }
]

export default data;